services:
  db:
    image: postgres:17
    container_name: mealbud-ai-dev-database
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      PORT: ${PORT}
      NEST_DATABASE_HOST: ${NEST_DATABASE_HOST}
      NEST_DATABASE_PORT: ${NEST_DATABASE_PORT}
      NEST_DATABASE_USER: ${NEST_DATABASE_USER}
      NEST_DATABASE_PASS: ${NEST_DATABASE_PASS}
      NEST_DATABASE_NAME: ${NEST_DATABASE_NAME}
    networks:
      - dev-network

volumes:
  pgdata:

networks:
  dev-network:
