version: "3.9"
services:
  # Database (PostgreSQL)
  db:
    image: postgres:15
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "${POSTGRES_DB}"]
      interval: 60s
      retries: 5
      start_period: 5s
      timeout: 10s

  # API (Nest.js)
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db
    restart: always
    ports:
      - "4000:4000"
    networks:
      - app-network
    healthcheck:
      test:
        ["CMD", "curl", "--silent", "--fail", "http://localhost:4000/health"]
      interval: 60s
      retries: 5
      start_period: 5s
      timeout: 10s

  # Web (Next.js)
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    environment:
      NEXT_API_URL: http://api:4000
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    depends_on:
      - api
    restart: always
    ports:
      - "3000:3000"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "http://localhost:3000/"]
      interval: 60s
      retries: 5
      start_period: 5s
      timeout: 10s

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
