import type { Metadata } from 'next';
import type { ReactNode } from 'react';
import { cookies } from 'next/headers';
import CookieBanner from '../components/cookie-banner/cookie-banner';
import { ThemeProvider } from '@/components/providers/theme-provider';
// import { PostHogProvider } from '@/components/providers/posthog-provider';
import { CookieConsentProvider } from '@/components/providers/cookie-consent-provider';
import { Space_Grotesk } from 'next/font/google';

import '@repo/ui/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const spaceGrotesk = Space_Grotesk({ subsets: ['latin'] });

type RootLayoutProps = Readonly<{
  children: ReactNode;
}>;

export default async function RootLayout({ children }: RootLayoutProps) {
  const cookieStore = await cookies();

  const initialConsent = cookieStore.get('cookieConsent')?.value === 'true';

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${spaceGrotesk.className}`}>
        <ThemeProvider>
          <CookieConsentProvider initialConsent={initialConsent}>
            <>{children}</>
            <CookieBanner />
          </CookieConsentProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
