name: "🔀 Pull Request Jobs"
on:
  pull_request:

permissions:
  contents: read

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 2

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Cache Turbo
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      # Cache build outputs for subsequent jobs
      - name: Cache node_modules, dist and .next directories
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
            **/dist
            **/.next
            !**/.next/cache
          key: ${{ runner.os }}-build-${{ github.sha }}

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      # Restore dependencies from cache
      - name: Restore cached node_modules
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-build-${{ github.sha }}

      - name: Restore Turbo cache
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Build project
        run: pnpm build

      # Cache build outputs for subsequent jobs
      - name: Cache build outputs
        uses: actions/cache@v4
        with:
          path: |
            **/dist
            **/.next
            !**/.next/cache
          key: ${{ runner.os }}-build-output-${{ github.sha }}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      # Restore dependencies from cache
      - name: Restore cached node_modules
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-build-${{ github.sha }}

      # Restore build outputs from cache
      - name: Restore build outputs
        uses: actions/cache@v4
        with:
          path: |
            **/dist
            **/.next
            !**/.next/cache
          key: ${{ runner.os }}-build-output-${{ github.sha }}

      - name: Restore Turbo cache
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Run lint
        run: pnpm lint

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      # Restore dependencies from cache
      - name: Restore cached node_modules
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-build-${{ github.sha }}

      # Restore build outputs from cache
      - name: Restore build outputs
        uses: actions/cache@v4
        with:
          path: |
            **/dist
            **/.next
            !**/.next/cache
          key: ${{ runner.os }}-build-output-${{ github.sha }}

      - name: Restore Turbo cache
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Run tests
        run: pnpm test

      # Upload coverage reports for potential future use
      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            **/coverage/
          retention-days: 7

  validate:
    name: Validate All Checks
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: All checks passed
        run: echo "✅ All checks have passed successfully!"
